server:
  port: 8080

spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://UserService
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**
        - id: health-record-service
          uri: lb://HealthRecordService
          predicates:
            - Path=/api/v1/records/**
        - id: notification-service
          uri: lb://NotificationService
          predicates:
            - Path=/api/v1/notifications/**
        - id: scheduling-service
          uri: lb://SchedulingService
          predicates:
            - Path=/api/v1/schedules/**
  profiles:
    active: docker

# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: gateway-service

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO
    fit.iuh.student.gatewayservice: DEBUG

---
# Docker profile configuration
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/