server:
  port: 8080

spring:
  application:
    name: GatewayService
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://UserService
          predicates:
            - Path=/api/v1/users/**, /api/v1/auth/**, /api/v1/upload/**
          filters:
            - AuthenticationFilter
        - id: health-record-service
          uri: lb://HealthRecordService
          predicates:
            - Path=/api/v1/records/**
          filters:
            - AuthenticationFilter
        - id: notification-service
          uri: lb://NotificationService
          predicates:
            - Path=/api/v1/notifications/**
          filters:
            - AuthenticationFilter
        - id: scheduling-service
          uri: lb://SchedulingService
          predicates:
            - Path=/api/v1/schedules/**
          filters:
            - AuthenticationFilter
  profiles:
    active: docker
jwt:
  secretKey: ${JWT_SECRET_KEY:defaultSecretKeyForDevelopment12345678901234567890}
  expiration: ${JWT_EXPIRATION:86400000}  # 24 hours in milliseconds
  header: Authorization
  prefix: Bearer
  refresh-token:
    expiration: ${JWT_REFRESH_EXPIRATION:604800000}  # 7 days in milliseconds
# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true
    hostname: gateway-service

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.web: INFO
    fit.iuh.student.gatewayservice: DEBUG

---
# Docker profile configuration
spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/