server:
  port: 8085

spring:
  application:
    name: CommunicationService
  data:
    mongodb:
      # MongoDB Atlas configuration (uncomment to use)
       uri: mongodb+srv://huyvu2379kh:${MONGODB_PSD}@communicationdb.yr4mous.mongodb.net/?retryWrites=true&w=majority&appName=CommunicationDB
  profiles:
    active: local
# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

# Logging Configuration
logging:
  level:
    org.springframework.data.mongodb: DEBUG
    fit.iuh.student.communicationservice: DEBUG
